org: joshgarnerdev
app: plex-ec2
service: plex-ec2-services-ec2
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:SendCommand
      Resource: 
        - arn:aws:ec2:#{AWS::Region}:#{AWS::AccountId}:instance/*
        - arn:aws:ssm:#{AWS::Region}::document/AWS-RunShellScript
    - Effect: Allow
      Action:
        - ssm:GetParametersByPath
      Resource: 
        - arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/plex-ec2/
    - Effect: Allow
      Action:
        - cloudformation:DescribeStacks
      Resource: 
        - arn:aws:cloudformation:#{AWS::Region}:#{AWS::AccountId}:stack/plex-vpc-ec2-${self:provider.stage}/*
        - arn:aws:cloudformation:#{AWS::Region}:#{AWS::AccountId}:stack/plex-ec2-resources-${self:provider.stage}/*
        - arn:aws:cloudformation:#{AWS::Region}:#{AWS::AccountId}:stack/plex-ec2-services-plex-${self:provider.stage}/*
        - arn:aws:cloudformation:#{AWS::Region}:#{AWS::AccountId}:stack/plex-ec2-services-ec2-${self:provider.stage}/*
  apiGateway:
    restApiId: 
      Fn::ImportValue: plex-ec2-resources-${self:provider.stage}-RestApiId
    restApiRootResourceId: 
      Fn::ImportValue: plex-ec2-resources-${self:provider.stage}-RestApiRootResourceId
  environment:
    stage: ${self:provider.stage}
    apiEndpoint: ${cf:${self:service}-${self:provider.stage}.ServiceEndpoint} 
custom:
  restApiId:
    Fn::ImportValue: plex-ec2-resources-dev-RestApiId
plugins:
  - serverless-pseudo-parameters
package:
  exclude:
    - node_modules/**
functions:
  stopEc2Instance:
    handler: functions/stopEc2Instance.handler
  startEc2Instance:
    handler: functions/startEc2Instance.handler
  searchTorrent:
    handler: functions/searchTorrent.handler
  setPlexClaimToken:
    handler: functions/setPlexClaimToken.handler
    events:
      - http:
          path: set-plex-claim-token
          method: get
resources:
  Conditions:
    CreateResources: 
      Fn::Equals:
        - ${ssm:/plex-ec2/create-resources, 'true'}
        - 'true'
  Resources:
    PlexRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: plexEc2Api
        Description: Plex Ec2 API Gateway
